#!/bin/bash

diskused=$( df -h | grep "/dev/sda1" | awk '{print $5}' ) # Uses the df command to look at space used in /dev/sdal

memfree=$( free -mh | grep Mem: | awk '{print $7}' ) # Uses the free command to tell us how much RAM we have unused on the system


connections=$( netstat | grep tcp ) #  Lists all active TCP connections from our machine

users=$( who | awk '{print $1}' ) # Lists all users currently logged in


echo -en "This is a snapshot of your current system:



		\e[36m	Disk Used: $diskused

		\e[33m	Free Memory: $memfree

		\e[91m	Logged in Users : $users

		\e[35m	Open Internet Connections: 

$connections


"
